export default {
  container: 'quicktab',
  tabBar: 'tab-bar',
  tabBarHide: 'hide',
  tabBarPrevItem: 'prev',
  tabBarRefreshItem: 'refresh',
  tabBarScrollItem: 'scroll',
  tabBarNextItem: 'next',
  tabBarDropdownItem: 'dropdown',
  tabBarFullscreenItem: 'fullscreen',
  tabBody: 'tab-body',
  //该类名实现iframe的鼠标事件穿透问题
  pointerEventsNnoe: 'pen',
  tabActive: 'active',
  tabDisabled: 'disabled',
  tabPaneActive: 'active',
  //关闭按钮鼠标移入时才显示时的辅助类名
  showCloseBtnOnHover: 'hover',
  listGroupCloseItem: 'close',
  listGroupShow: 'show',
  listGroupCloseOtherItem: 'other',
  listGroupClosePrevItem: 'prev',
  listGroupCloseNextItem: 'next',
  listGroupCloseAllItem: 'all',
  listGroupRefreshItem: 'refresh',
  listGroupCenterActiveItem: 'center-active',
  listGroupNewBlankItem: 'new-blank',
  listGroupFullscreenItem: 'fullscreen',
  //遮罩层
  overlays: 'mask',
}
